name: ogents
description: An AI agent with atSign that processes file notifications and summarizes files using LLM.
version: 1.0.0
repository: https://github.com/cconstab/ogents

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  at_client: ^3.2.11
  at_commons: ^5.0.3
  at_utils: ^3.0.17
  at_cli_commons: ^1.0.1
  at_onboarding_cli: ^1.3.1
  at_lookup: ^3.0.46
  http: ^1.1.0
  path: ^1.8.3
  uuid: ^3.0.7
  logging: ^1.2.0
  args: ^2.4.2
  mime: ^1.0.4
  archive: ^3.4.9
  crypto: ^3.0.3
  chalkdart: ^2.0.8

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
