name: ogents
description: An AI agent with atSign that processes file notifications and summarizes files using LLM.
version: 1.0.0
repository: https://github.com/cconstab/ogents

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  at_client: ^3.4.2
  at_commons: ^5.0.3
  at_utils: ^3.0.17
  at_cli_commons: ^1.3.0
  http: ^1.1.0
  logging: ^1.2.0
  path: ^1.8.3
  archive: ^3.4.10
  args: ^2.4.2
  mime: ^1.0.4
  chalkdart: ^2.4.0
  uuid: ^3.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
